In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import time
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

df = pd.read_csv('/content/drive/MyDrive/Machine Learning Project - 605/KMeans/yellow_tripdata.csv', header=None, low_memory=False)

In [ ]:
df.columns = df.iloc[0]
df = df[1:].reset_index(drop=True)

In [ ]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,2016-03-01 00:00:00,2016-03-01 00:07:55,1,2.50,-73.97674560546875,40.765151977539062,1,N,-74.004264831542969,40.746128082275391,1,9,0.5,0.5,2.05,0,0.3,12.35
1,1,2016-03-01 00:00:00,2016-03-01 00:11:06,1,2.90,-73.983482360839844,40.767925262451172,1,N,-74.005943298339844,40.733165740966797,1,11,0.5,0.5,3.05,0,0.3,15.35
2,2,2016-03-01 00:00:00,2016-03-01 00:31:06,2,19.98,-73.782020568847656,40.644809722900391,1,N,-73.974540710449219,40.675769805908203,1,54.5,0.5,0.5,8,0,0.3,63.8
3,2,2016-03-01 00:00:00,2016-03-01 00:00:00,3,10.78,-73.863418579101562,40.769813537597656,1,N,-73.969650268554688,40.757766723632812,1,31.5,0,0.5,3.78,5.54,0.3,41.62
4,2,2016-03-01 00:00:00,2016-03-01 00:00:00,5,30.43,-73.97174072265625,40.792182922363281,3,N,-74.177169799804688,40.695053100585937,1,98,0,0,0,15.5,0.3,113.8

In [ ]:
df.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'pickup_longitude',
       'pickup_latitude', 'RatecodeID', 'store_and_fwd_flag',
       'dropoff_longitude', 'dropoff_latitude', 'payment_type', 'fare_amount',
       'extra', 'mta_tax', 'tip_amount', 'tolls_amount',
       'improvement_surcharge', 'total_amount'],
      dtype='object', name=0)

In [ ]:
features = [
    'passenger_count', 'trip_distance', 'pickup_longitude', 'pickup_latitude',
    'dropoff_longitude', 'dropoff_latitude', 'fare_amount', 'extra',
    'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge'
]
target = 'total_amount'

In [ ]:
df = df.apply(pd.to_numeric, errors='coerce')

In [ ]:
df.dtypes

0
VendorID                   int64
tpep_pickup_datetime     float64
tpep_dropoff_datetime    float64
passenger_count            int64
trip_distance            float64
pickup_longitude         float64
pickup_latitude          float64
RatecodeID                 int64
store_and_fwd_flag       float64
dropoff_longitude        float64
dropoff_latitude         float64
payment_type               int64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
dtype: object

In [ ]:
X = df[features]
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

# CPU Training
start_cpu = time.time()

knn_cpu = KNeighborsRegressor(n_neighbors=5)
knn_cpu.fit(X_train, y_train)

end_cpu = time.time()
print(f"CPU Training Time: {end_cpu - start_cpu:.4f} seconds")

CPU Training Time: 67.7663 seconds

In [ ]:
# CPU Prediction
start_cpu_pred = time.time()

y_pred_cpu = knn_cpu.predict(X_test)

end_cpu_pred = time.time()
print(f"CPU Prediction Time: {end_cpu_pred - start_cpu_pred:.4f} seconds")

CPU Prediction Time: 1050.7053 seconds

In [ ]:
import psutil, os
def print_memory_usage_gb():
    # CPU RAM usage
    process = psutil.Process(os.getpid())
    ram_usage_gb = process.memory_info().rss / (1024 ** 3)  # <<< divide by 1024³
    print(f"CPU RAM Usage: {ram_usage_gb:.4f} GB")

print_memory_usage_gb()

CPU RAM Usage: 9.4378 GB